2020/11/03 16:50:14 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 16:50:17 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /src HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 16:50:44 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /src HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 16:50:44 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /src HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 16:50:44 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /src HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 16:50:45 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /src HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:39:48 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:39:48 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/03 18:39:51 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /src HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:39:51 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/src"
2020/11/03 18:40:21 [error] 28#28: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:40:21 [error] 28#28: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/03 18:40:25 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:40:25 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/03 18:40:34 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:40:34 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/03 18:45:26 [error] 28#28: *26 FastCGI sent in stderr: "PHP message: 2020-11-03T18:45:26+00:00 [critical] Uncaught Exception: Class "App\Controller\AbstractController" not found while loading "App\Controller\CurrencyController"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /currency HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/03 18:47:02 [error] 28#28: *28 FastCGI sent in stderr: "PHP message: 2020-11-03T18:47:02+00:00 [critical] Uncaught Exception: Failed to remove directory "/var/www/var/cache/dev/ContainerI7NumP9": rmdir(/var/www/var/cache/dev/ContainerI7NumP9): Directory not empty" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /currency HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:16:18 [error] 29#29: *109 FastCGI sent in stderr: "PHP message: 2020-11-04T21:16:18+00:00 [critical] Uncaught Error: syntax error, unexpected 'use' (T_USE), expecting ';' or ','" while reading upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:41 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:43 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:43 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:44 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:45 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:45 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:46 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:48 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:48 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "POST /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:56 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:58 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:59 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:37:59 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:13 [error] 28#28: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:13 [error] 28#28: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:23 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:23 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:23 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:23 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:24 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:24 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:25 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:25 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:25 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:25 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:38:27 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /save HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:27 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/save"
2020/11/04 21:38:30 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 21:38:30 [error] 28#28: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/11/04 21:59:01 [error] 28#28: *55 FastCGI sent in stderr: "PHP message: 2020-11-04T21:59:01+00:00 [critical] Uncaught Error: syntax error, unexpected ';', expecting ']'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /getValues HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/04 22:08:52 [error] 28#28: *64 FastCGI sent in stderr: "PHP message: 2020-11-04T22:08:52+00:00 [critical] Uncaught Error: syntax error, unexpected ']'" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /getValues HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/11/05 14:57:40 [error] 28#28: *1 FastCGI sent in stderr: "PHP message: 2020-11-05T14:57:40+00:00 [critical] Uncaught Exception: Failed to remove directory "/var/www/var/cache/dev/ContainerPZxiZ2H": rmdir(/var/www/var/cache/dev/ContainerPZxiZ2H): Directory not empty" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /getCurrencies HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
